### ISSUE TITLE
Please add a license (e.g. MIT license)

### ISSUE THREAD

**Issue by kolibri52** [mschneiderbauer/GS1Parser#1]
Hi Marlene,
Thanks for your solutions. I would appreciate it very much, if you could add a license to this repository,
so that I'm allowed to make a copy and changes in my own clone.
The MIT license would be great.

I would like to make a clone where I would like to add some helper functions, so that it is possible to integrate it in a LabVIEW Project.
Instead of .net core it would be based at .NET Framework, which is easier to integrate it in LabVIEW under Windows.
Of course, I would point to your repository as the original. If you have wishes for the wording, I can gladly take that into account.

Thanks for your help.
Best, Jonathan

**Comment by mschneiderbauer** [comment]
Hi, thanks for the request. I have added the license and am glad to help. 

Kind regards
Marlene
